#!/usr/bin/env bash
cd $HOME
echo Running Ali3aber Fully ilauncher
sudo chmod 777 II
sudo chmod 777 keepercli/kp.sh
sudo chmod 777 helperapi/hp.sh
sudo chmod 777 keepercli/libs/tgcli
sudo apt-get update
sudo apt-get upgrade
keeper() {
./keepercli/kp.sh
}
helper() {
./helperapi.sh
}
red() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
green() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
white() {
  printf '\e[1;37m%s\n\e[0;39;49m' "$@"
}
if [ "$1" = "keeper" ]; then
	install
elif [ "$1" = "helper" ]; then
	update
else

green "Ali3aber is Running iBot Service"
white "iBot Done"
fi
